# Generated by Django 6.0.3 on 2026-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct image URL (e.g., https://i.imgur.com/example.jpg)', null=True),
        ),
    ]
