# Generated by Django 6.0.3 on 2026-04-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_blogpost_image_blogpost_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste image URL (e.g., from Unsplash, Pexels, etc.)', null=True),
        ),
    ]
